version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:11.9.0
  
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn run test:ci
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn run build
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  test_build_publish:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - develop
                - master

